### ISSUE TITLE
MELPAに登録

### ISSUE THREAD

**Issue by ncaq** [ncaq/flycheck-ensime#3]
ドキュメント整備が必要っぽい

**Comment by ncaq** [comment]
pull requst作った
[added: flycheck-ensime by ncaq · Pull Request #5978 · melpa/melpa](https://github.com/melpa/melpa/pull/5978)

**Comment by fommil** [comment]
This line

```
;; Package-Requires: ((emacs "26")(ensime "2.0.0")(flycheck "31"))
```

means that you need to be GPL 3.0.

You could also just add this feature to `ensime-emacs`.

**Comment by fommil** [comment]
btw, you could also write a backend that just uses sbt and `ensimeCompileOnly` from the sbt plugin :smile: 

When the dependencies are compiled, that would give you completely accurate errors since it uses the real compiler not the (broken) presentation compiler. And it'd be pretty fast too! And you wouldn't need to bring up an ensime server.

**Comment by ncaq** [comment]
> means that you need to be GPL 3.0.

I think to can use MIT license.
Because I do not link with GPL program.

> You could also just add this feature to `ensime-emacs`.

Once upon a time I heard that "why ensime does not support flycheck?"
Because it was answered as "political reason" (tweet has been deleted),
I created a package thinking that it is only necessary to make it from the outside.

> btw, you could also write a backend that just uses sbt and `ensimeCompileOnly` from the sbt plugin smile

I do not know well because I do not know sbt so far ...

**Comment by ncaq** [comment]
I rather love the GPL (I am self evident at the point of GNU Emacs loyalty).
I do not think that I want to put strong constraints on such a short simple code.

**Comment by ncaq** [comment]
とりあえずMELPAには登録されたのでこのissueはcloseします

**Comment by fommil** [comment]
given that Emacs and emacs-lisp, and your dependencies, are all GPL-3, I don't think it makes any sense to try and hold out for a pushover license like MIT :man_shrugging:

Whover said that ensime doesn't use flycheck for "politics" was talking bullshit. When I was maintaining ensime I'd have been happy to accept this (with flycheck as an optional dependency)... and I think `emacs-scala-mode` would benefit from the `ensimeCompileOnly` sbt backend mentioned above (I considered writing it myself several times).

**Comment by fommil** [comment]
btw, you can use any tool in place of `ensimeCompileOnly`. You just need a warm JVM and a way to invoke the compiler on the current file (with the correct flags), then grab the output.

**Comment by ncaq** [comment]
> given that Emacs and emacs-lisp, and your dependencies, are all GPL-3, I don't think it makes any sense to try and hold out for a pushover license like MIT man_shrugging

OK, I use GPL-3.
I love GPL.

**Comment by ncaq** [comment]
Please see [changed: license: MIT -> GPL-3 · ncaq/flycheck-ensime@9fe000e](https://github.com/ncaq/flycheck-ensime/commit/9fe000e7004725bc8c3b7554237d717bca9cd9ac)

**Comment by ncaq** [comment]
To tell the truth.
The purpose I wrote this Emacs Lisp program was about 2016 when I was assigned to a project I was not involved from the beginning,
When I tried to fix the old Scala program full of warnings with Emacs I wrote that I thought "Warning list will not appear!"
Recently I do not write Scala in business, so I do not have much motivation.
When involved in defeat processing, motivation may come up ...
Since the project uses the old Play framework and uses the Activator instead of sbt for the build, I do not even know whether a modern method can be used.
If you look at this program and gain inspiration and incorporate flycheck into ensime, I am honored rather than thinking regrettably.

**Comment by fommil** [comment]
I do not write Scala either :smile: I would have done it this way in hindsight. And I also would have used the build tool to populate flycheck. People are excited by Metals using the real compiler... but it is very easy to set this up, I just never thought to do it.

**Comment by ncaq** [comment]
Well when I wrote this, there were only options ENSIME.
Now is the age of LSP…

**Comment by fommil** [comment]
*sigh* yeah... and the age of forgetting what already exists https://github.com/ensime/ensime-server/tree/3.0/lsp/src/main/scala/org/ensime/lsp
